[package]
name = "raft"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
prost = "0.12"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"

[build-dependencies]
tonic-build = "0.11"
